<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
		<RootNamespace>ocpa.ro.api</RootNamespace>
		<AssemblyName>ocpa.ro.api</AssemblyName>
		<WarningsAsErrors>true</WarningsAsErrors>
		<WarningLevel>5</WarningLevel>
		<LangVersion>latest</LangVersion>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.22.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
		<PackageReference Include="Serilog" Version="4.4.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ocpa.ro.application\ocpa.ro.application.csproj" />
	  <ProjectReference Include="..\ocpa.ro.infrastructure\ocpa.ro.infrastructure.csproj" />
	  <ProjectReference Include="..\ocpa.ro.persistence\ocpa.ro.persistence.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Template.db3">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
