<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <RootNamespace>ocpa.ro.persistence</RootNamespace>
      <AssemblyName>ocpa.ro.persistence</AssemblyName>
      <WarningsAsErrors>true</WarningsAsErrors>
      <WarningLevel>5</WarningLevel>
      <LangVersion>latest</LangVersion>
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="x\**" />
    <EmbeddedResource Remove="x\**" />
    <None Remove="x\**" />
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\ocpa.ro.application\ocpa.ro.application.csproj" />
  </ItemGroup>

</Project>
