//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AppMenu {
    id?: number;
    name?: string | undefined;
    url?: string | undefined;
    displayMode?: EMenuDisplayMode;
    menuIcon?: string | undefined;
    userId?: number | undefined;
    appName?: string | undefined;
    adminMode?: boolean;
}

export interface Application {
    id?: number;
    name?: string | undefined;
    code?: string | undefined;
    loginRequired?: boolean;
    adminMode?: boolean;
    builtin?: boolean;
}

export interface ApplicationMenu {
    id?: number;
    applicationId?: number | undefined;
    menuId?: number;
}

export interface ApplicationUser {
    id?: number;
    applicationId?: number;
    userId?: number;
}

export interface AuthenticationResponse {
    loginId: string;
    anonymizedEmail: string;
    token: string;
    type: number;
    validity: number;
    sendOTP: boolean;
}

export enum EMenuDisplayMode {
    AlwaysHide = "AlwaysHide",
    AlwaysShow = "AlwaysShow",
    HideOnMobile = "HideOnMobile",
    ShowOnMobile = "ShowOnMobile",
}

export interface FailedAuthenticationResponse {
    errorMessage?: string | undefined;
    loginAttemptsRemaining?: number;
}

export interface Menu {
    id?: number;
    name?: string | undefined;
    url?: string | undefined;
    displayModeId?: number | undefined;
    menuIcon?: string | undefined;
    builtin?: boolean;
}

export interface Menus {
    publicMenus?: VMenu[] | undefined;
    appMenus?: AppMenu[] | undefined;
    deviceId?: string | undefined;
}

export interface RegisteredDevice {
    id?: number;
    deviceId?: string | undefined;
    lastLoginId?: string | undefined;
    lastLoginIpAddress?: string | undefined;
    lastLoginTimestamp?: Date;
    lastLoginGeoLocation?: string | undefined;
}

export interface User {
    id?: number;
    loginId?: string | undefined;
    passwordHash?: string | undefined;
    type?: number;
    enabled?: boolean;
    loginAttemptsRemaining?: number;
    emailAddress?: string | undefined;
    useOtp?: boolean;
}

export interface UserType {
    id?: number;
    code?: string | undefined;
    description?: string | undefined;
}

export interface VMenu {
    id?: number;
    name?: string | undefined;
    url?: string | undefined;
    displayMode?: EMenuDisplayMode;
    menuIcon?: string | undefined;
}

export interface Body {
    LoginId: string;
    Password: string;

    [key: string]: any;
}

export interface Body2 {
    LoginId: string;
    Password: string;

    [key: string]: any;
}