//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface ContentUnit {
    type?: ContentUnitType;
    name?: string | undefined;
    path?: string | undefined;
    size?: number;
    children?: ContentUnit[] | undefined;
    selected?: boolean;
    expanded?: boolean;
}

export enum ContentUnitType {
    None = "None",
    Folder = "Folder",
    MarkdownIndexFolder = "MarkdownIndexFolder",
    File = "File",
}