//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface BuildInfo {
    title?: string | undefined;
    version?: BuildVersion;
    buildDate?: Date;
    isRelease?: boolean;
    comment?: string | undefined;
    url?: string | undefined;
}

export interface BuildVersion {
    major?: number;
    minor?: number;
    build?: number;
}

export interface CalendarRange {
    start?: Date;
    end?: Date;
    length?: number;
}

export interface CityDetail {
    id?: number;
    regionId?: number;
    name?: string | undefined;
    subregion?: string | undefined;
    lat?: number;
    lon?: number;
    isDefault?: boolean;
    regionName?: string | undefined;
    regionCode?: string | undefined;
}

export interface GeoLocation {
    status?: string | undefined;
    continent?: string | undefined;
    continentCode?: string | undefined;
    country?: string | undefined;
    countryCode?: string | undefined;
    region?: string | undefined;
    regionName?: string | undefined;
    city?: string | undefined;
    district?: string | undefined;
    zip?: string | undefined;
    lat?: number;
    lon?: number;
    timezone?: string | undefined;
    offset?: number;
    currency?: string | undefined;
    isp?: string | undefined;
    org?: string | undefined;
    as?: string | undefined;
    asname?: string | undefined;
    reverse?: string | undefined;
    mobile?: boolean;
    proxy?: boolean;
    hosting?: boolean;
}

export interface GridCoordinates {
    r?: number;
    c?: number;
}

export interface MeteoDailyData {
    date?: string | undefined;
    tMinActual?: number;
    tMaxActual?: number;
    tMinNormal?: number;
    tMaxNormal?: number;
    forecast?: string | undefined;
    tempFeel?: string | undefined;
    hazards?: string[] | undefined;
    wind?: number;
    windDirection?: WindDirection;
    precip?: number;
    snowCover?: number;
    soilRain?: number;
    instability?: number;
    fog?: number;
    rain?: number;
    snow?: number;
    p00?: number;
    p01?: number;
}

export interface MeteoData {
    name?: string | undefined;
    dbi?: number;
    calendarRange?: CalendarRange;
    readonly dataCount?: number;
    status?: MeteoDbStatus;
    region?: string | undefined;
    gridCoordinates?: GridCoordinates;
    data?: { [key: string]: MeteoDailyData; } | undefined;
}

export interface MeteoDbInfo {
    name?: string | undefined;
    dbi?: number;
    calendarRange?: CalendarRange;
    readonly dataCount?: number;
    status?: MeteoDbStatus;
}

export enum MeteoDbStatus {
    Absent = "Absent",
    Offline = "Offline",
    Online = "Online",
}

export interface RegionDetail {
    id?: number;
    name?: string | undefined;
    code?: string | undefined;
    minLon?: number;
    maxLon?: number;
    minLat?: number;
    maxLat?: number;
    gridResolution?: number;
    subregions?: string[] | undefined;
}

export enum WindDirection {
    W = "W",
    WSW = "WSW",
    SW = "SW",
    SSW = "SSW",
    S = "S",
    SSE = "SSE",
    SE = "SE",
    ESE = "ESE",
    E = "E",
    ENE = "ENE",
    NE = "NE",
    NNE = "NNE",
    N = "N",
    NNW = "NNW",
    NW = "NW",
    WNW = "WNW",
}